namespace: wooglife

cronjob:
  name: scrapers
  image: ghcr.io/woog-life/scrapers:__TAG__
  imagePullPolicy: IfNotPresent
  schedule: "CRON_TZ=UTC */30 * * * *"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: scrapers
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

secret:
  name: scrapers-api-key
  apiKey: __API_KEY__
