name: Build image

on:
  push:
    branches:
      - '!master'

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/scrapers:${GITHUB_SHA} .
