name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/scrapers:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/woog-life/scrapers:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: [build_push_docker, lint]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: update telegram token in manifest.yml
        run: sed -i -e "s#__API_KEY__#${{ secrets.API_KEY }}#g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          release_name: scrapers
          ref: .
          namespace: wooglife
          install: true
          atomic: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}